import { PatientCaseRecord } from './masterPatientRecord';
import { queryMedGemma, tpaQuerySchema } from './llmClient';
import { getInsurerPolicyRules } from './policyConfigService';

export interface PredictedQuery {
    category: 'billing' | 'clinical' | 'administrative' | 'policy';
    queryText: string;
    reason: string;
    severity: 'blocking' | 'advisory';
    mitigation: string;
    /** Whether this query was generated by a deterministic compliance rule or open-ended AI inference */
    source: 'rule_verified' | 'ai_suggested';
}

export interface TpaQueryPredictionResult {
    predictedQueries: PredictedQuery[];
}

export async function predictTpaQueries(caseRecord: PatientCaseRecord): Promise<TpaQueryPredictionResult> {
    const queries: PredictedQuery[] = [];
    const rawRecord = caseRecord.rawPreAuthRecord || {};

    // Extract values
    const sumInsured = caseRecord.insuranceDetails?.sumInsured || rawRecord.insurance?.sumInsured || 500000;
    const insurerName = caseRecord.insuranceDetails?.insurer || rawRecord.insurance?.insurerName || '';
    const roomRentPerDay = rawRecord.costEstimate?.roomRentPerDay || 0;
    const roomCategory = (rawRecord.admission?.roomCategory || '').toLowerCase();
    const expectedRoomDays = rawRecord.costEstimate?.expectedRoomDays || rawRecord.admission?.expectedDaysInRoom || 0;
    const expectedIcuDays = rawRecord.costEstimate?.expectedDaysInICU || rawRecord.admission?.expectedDaysInICU || 0;
    const expectedLengthOfStay = rawRecord.admission?.expectedLengthOfStay || 0;
    const diagnosisText = caseRecord.encounters?.[0]?.diagnosis || '';
    const diagLower = diagnosisText.toLowerCase();

    // Check daycare exemption status (exempt daycare/short stays under 24 hours from stay extension reviews)
    const isDaycare = diagLower.includes('cataract') || diagLower.includes('phaco') || 
                      expectedLengthOfStay <= 1 || (expectedRoomDays + expectedIcuDays) <= 1;

    // RULE 1: Room Rent Capping & Proportional Deductions
    if (roomRentPerDay > 0 && sumInsured > 0) {
        const isIcu = roomCategory.includes('icu') || roomCategory.includes('iccu') || roomCategory.includes('nicu');
        
        // Resolve cap percentages from config
        const policyRules = getInsurerPolicyRules();
        const matchedRule = policyRules.find(r => insurerName.toLowerCase().includes(r.insurerName.toLowerCase())) || 
                            { wardCapPercent: 0.01, icuCapPercent: 0.02 };
                            
        const capPercentage = isIcu ? matchedRule.icuCapPercent : matchedRule.wardCapPercent;
        const rentCap = sumInsured * capPercentage;
        
        if (roomRentPerDay > rentCap) {
            const deductionRatio = Math.round((rentCap / roomRentPerDay) * 100);
            queries.push({
                category: 'billing',
                queryText: `Discrepancy in room rent. Actual ward/ICU rent ₹${roomRentPerDay.toLocaleString('en-IN')}/day exceeds policy limit (₹${rentCap.toLocaleString('en-IN')}/day). Proportional deductions will apply to all associated hospital charges.`,
                reason: `Room category cap exceeded. Limit is ${isIcu ? '2%' : '1%'} of SI (SI: ₹${sumInsured.toLocaleString('en-IN')}, Cap: ₹${rentCap.toLocaleString('en-IN')}/day, Actual: ₹${roomRentPerDay.toLocaleString('en-IN')}/day).`,
                severity: 'blocking',
                mitigation: `Change the room type to match the policy cap (₹${rentCap}/day) or counsel the patient on out-of-pocket proportional share (${100 - deductionRatio}% co-payment on bills).`,
                source: 'rule_verified',
            });
        }
    }

    // RULE 2: Stay Duration Audit (Daycare is exempt, otherwise check clinical justification)
    if (!isDaycare && expectedLengthOfStay > 3) {
        // Check if there is a clinical reason/extension justified
        const narrative = [
            caseRecord.encounters?.[0]?.chiefComplaints || '',
            caseRecord.encounters?.[0]?.historyOfPresentIllness || '',
            caseRecord.encounters?.[0]?.relevantClinicalFindings || '',
            rawRecord.clinical?.additionalClinicalNotes || ''
        ].join(' ').toLowerCase();

        const hasJustification = narrative.includes('complication') || narrative.includes('fever') || 
                                 narrative.includes('monitoring') || narrative.includes('sepsis') || 
                                 narrative.includes('severe') || narrative.includes('icu') ||
                                 narrative.includes('extended') || narrative.includes('justification');

        if (!hasJustification) {
            queries.push({
                category: 'clinical',
                queryText: `Please justify the proposed stay duration of ${expectedLengthOfStay} days for ${diagnosisText || 'patient'}. Stays exceeding standard 3 days require explicit clinical justification.`,
                reason: `Length of stay exceeds standard duration (${expectedLengthOfStay} days) without explicit extension reason in clinical notes.`,
                severity: 'advisory',
                mitigation: `Update the clinical notes in Pre-Auth Step 2 to detail clinical reasons (e.g. daily temperature spikes, abnormal lab counts, antibiotic monitoring).`,
                source: 'rule_verified',
            });
        }
    }

    // RULE 3: Pre-Existing Disease (PED) Waiting Periods & Comorbidities
    const comorbidities: string[] = [];
    const pastHistory = rawRecord.admission?.pastMedicalHistory || {};
    if (pastHistory.diabetes?.present) comorbidities.push(`diabetes (duration: ${pastHistory.diabetes.duration || 'unknown'})`);
    if (pastHistory.hypertension?.present) comorbidities.push(`hypertension (duration: ${pastHistory.hypertension.duration || 'unknown'})`);
    if (pastHistory.heartDisease?.present) comorbidities.push('heart disease');
    if (pastHistory.kidney?.present) comorbidities.push('kidney disease');

    // Cardiac/Stroke primary diagnosis mapping to comorbidities
    const isCardiacOrStroke = diagLower.includes('stroke') || diagLower.includes('infarct') || 
                              diagLower.includes('cardiac') || diagLower.includes('heart') || 
                              diagLower.includes('cad') || diagLower.includes('mi') || 
                              diagLower.includes('angina') || diagLower.includes('mca') || 
                              diagLower.includes('ischemic');

    if (isCardiacOrStroke && comorbidities.length > 0) {
        queries.push({
            category: 'policy',
            queryText: `Primary diagnosis (${diagnosisText}) is highly correlated with documented comorbidities: ${comorbidities.join(', ')}. Please confirm if this is a pre-existing condition, subject to waiting period clauses.`,
            reason: `Co-relation of primary cardiovascular/neurological condition with comorbidities: ${comorbidities.join(', ')}.`,
            severity: 'blocking',
            mitigation: `Provide a treating physician declaration certifying that this is an acute onset episode, and attach the patient's past 3 years' medical insurance renewals to bypass the waiting period.`,
            source: 'rule_verified',
        });
    }

    // Run AI Fallback prediction for remaining categories or more complex clinical queries
    try {
        const prompt = `You are a Third Party Administrator (TPA) medical reviewer auditing a pre-authorization request for an Indian hospital stay.
Analyze the following clinical and policy details and predict any potential query objections or rejections a TPA reviewer would raise.

Patient Profile:
- Name: ${caseRecord.patientProfile?.name || 'Incomplete'}
- Age: ${caseRecord.patientProfile?.age || 0}
- Gender: ${caseRecord.patientProfile?.gender || 'Unknown'}

Insurance Details:
- Insurer: ${caseRecord.insuranceDetails?.insurer || 'Unknown'}
- TPA: ${caseRecord.insuranceDetails?.TPA || 'Unknown'}
- Sum Insured: ₹${sumInsured}

Clinical Narrative:
- Chief Complaints: ${caseRecord.encounters?.[0]?.chiefComplaints || 'None'}
- Primary Diagnosis: ${diagnosisText || 'None'} (ICD-10: ${rawRecord.clinical?.diagnoses?.[0]?.icd10Code || 'Pending'})
- History of Present Illness: ${caseRecord.encounters?.[0]?.historyOfPresentIllness || 'None'}
- Proposed Treatment: ${rawRecord.clinical?.proposedLineOfTreatment?.surgical ? 'Surgical' : 'Medical'}

Cost Summary:
- Estimated Cost: ₹${rawRecord.costEstimate?.totalEstimatedCost || 0}
- Room Category: ${rawRecord.admission?.roomCategory || 'Ward'}
- Length of stay: ${expectedLengthOfStay} days

Return a list of predicted queries in the requested JSON format. Avoid repeating the deterministic billing room rent caps or cardiovascular comorbidity queries if they are already flagged. Do not generate queries if the case is standard and fully documented.`;

        const systemInstruction = `You are a TPA claim auditor. Output a valid JSON object matching the response schema:
{
  "predictedQueries": [
    {
      "category": "billing" | "clinical" | "administrative" | "policy",
      "queryText": "string",
      "reason": "string",
      "severity": "blocking" | "advisory",
      "mitigation": "string"
    }
  ]
}
Return only valid JSON.`;

        const aiOutputStr = await queryMedGemma(prompt, systemInstruction, tpaQuerySchema);
        const parsed = JSON.parse(aiOutputStr);
        if (parsed && Array.isArray(parsed.predictedQueries)) {
            for (const q of parsed.predictedQueries) {
                // Deduplicate queries
                const exists = queries.some(existing => 
                    existing.category === q.category && 
                    existing.queryText.toLowerCase().includes(q.queryText.toLowerCase().slice(0, 10))
                );
                if (!exists) {
                    // Stamp source at merge time — never trust the model to self-report this
                    queries.push({ ...q, source: 'ai_suggested' as const });
                }
            }
        }
    } catch (err) {
        console.error("[tpaQueryPredictionService] LLM fallback prediction failed:", err);
    }

    return { predictedQueries: queries };
}
