
import React from 'react';
import { Icon } from './Icon';
import { renderMarkdownToHTML } from '../utils/markdownRenderer';

interface CaseSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summaryContent: string | null;
  isGenerating: boolean;
  chatTitle: string;
}

const SummaryContent: React.FC<{ content: string; title: string }> = ({ content, title }) => (
    <div className="printable-area p-4 bg-white text-black font-sans">
        <header className="border-b-2 brand-border border-black pb-2 mb-4">
            <h1 className="text-2xl font-bold text-aivana-accent">Clinical Case Summary</h1>
            <p className="text-sm text-gray-600">From conversation: "{title}"</p>
        </header>
        <main 
            className="prose prose-sm max-w-none"
            dangerouslySetInnerHTML={{ __html: renderMarkdownToHTML(content) }}
        />
        <footer className="mt-6 pt-2 border-t border-gray-400 text-center text-xs text-gray-500">
            <p>This summary was generated by Aivana AI based on the conversation history. It is intended for documentation and handover purposes and should be verified by the clinician.</p>
        </footer>
    </div>
);


export const CaseSummaryModal: React.FC<CaseSummaryModalProps> = ({ isOpen, onClose, summaryContent, isGenerating, chatTitle }) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    // Force move printable area to body to bypass Modal nesting styles during print
    const printable = document.querySelector('.printable-area');
    if (printable) {
        const originalParent = printable.parentElement;
        document.body.appendChild(printable);
        window.print();
        setTimeout(() => {
            if (originalParent) originalParent.appendChild(printable);
        }, 100);
    } else {
        window.print();
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center transition-opacity no-print"
      aria-modal="true"
      role="dialog"
    >
      <div className="bg-aivana-grey rounded-2xl shadow-xl w-full max-w-4xl m-4 transform transition-all text-white border border-aivana-light-grey flex flex-col max-h-[90vh]">
        <header className="p-4 flex-shrink-0 flex justify-between items-center border-b border-aivana-light-grey">
            <div className="flex items-center gap-3">
                <Icon name="document-text" className="w-6 h-6 text-aivana-accent" />
                <h2 className="text-xl font-bold">Case Summary</h2>
            </div>
             <button onClick={onClose} className="p-1 rounded-full hover:bg-aivana-light-grey">
                <Icon name="close" className="w-5 h-5"/>
            </button>
        </header>
        
        <div className="flex-1 p-4 overflow-y-auto bg-gray-800 custom-scrollbar">
            {isGenerating && (
                <div className="flex flex-col items-center justify-center h-full text-gray-400">
                    <div className="w-8 h-8 border-4 border-t-transparent border-aivana-accent rounded-full animate-spin mb-4"></div>
                    <p>Generating summary from conversation...</p>
                </div>
            )}
            {!isGenerating && summaryContent && (
                <SummaryContent content={summaryContent} title={chatTitle} />
            )}
        </div>
        
        <footer className="p-4 flex-shrink-0 flex justify-end items-center border-t border-aivana-light-grey">
            <button
                onClick={handlePrint}
                disabled={isGenerating || !summaryContent}
                className="bg-aivana-accent hover:bg-purple-700 text-white font-semibold py-2 px-6 rounded-lg transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
            >
                <Icon name="print" className="w-5 h-5"/>
                Print Summary
            </button>
        </footer>
      </div>
    </div>
  );
};
