/**
 * adversarialSafetyQA.ts
 *
 * PURPOSE: Stress-test the fail-safe property of the Aivana readiness engine.
 *
 * This is NOT a score-accuracy test. It tests a single safety invariant:
 *
 *   "For any input whose ICD-10 code is not in the engine's requirement map,
 *    the engine MUST return needsManualReview=true AND score ≤ 40."
 *
 * The cases below are deliberately crafted — NOT generated by Gemini — so they
 * have zero DNA overlap with the cases that were used to design the fix.
 *
 * Categories tested:
 *   A. Genuinely unmapped but valid ICD-10 codes (rare/obscure conditions)
 *   B. Edge-case boundary codes (adjacent to mapped prefixes)
 *   C. Malformed / invalid code strings
 *   D. Clinically severe but unmapped conditions (the most dangerous category)
 *   E. Empty / null / missing diagnosis inputs
 *   F. Text-only diagnoses with no ICD-10 code
 *   G. Codes that LOOK like they might match a mapped prefix but don't
 *
 * A "slip-through" bug = any case where needsManualReview is false OR score > 40
 * while the input is not in the mapped set.
 */

import { computeReadiness } from '../../utils/readinessScore';
import { isIcdMapped } from '../../utils/documentRequirements';
import { PreAuthRecord } from '../../components/PreAuthWizard/types';

// ─── helpers ──────────────────────────────────────────────────────────────────

const SAFE_SCORE_CEILING = 40; // max score allowed for an unmapped condition
const PASS = '✅ PASS';
const FAIL = '❌ FAIL  ← SLIP-THROUGH BUG';

interface AdversarialCase {
    label: string;
    category: string;
    icd10Code: string;
    diagnosisText: string;
    expectMapped: boolean; // true = we expect the engine to KNOW this code
}

// Minimal fully-populated record that removes all OTHER scoring penalties
// (so the only deduction that should fire is the unmapped-condition penalty)
function buildFullRecord(icd10Code: string, diagnosisText: string): Partial<PreAuthRecord> {
    return {
        id: 'ADV-TEST',
        status: 'draft',
        patient: {
            patientName: 'Test Patient',
            age: 45,
            gender: 'Male',
            mobileNumber: '9876543210',
            city: 'Pune',
            state: 'Maharashtra',
        },
        insurance: {
            insurerName: 'Star Health',
            tpaName: 'Medi Assist',
            policyNumber: 'POL-12345',
            policyType: 'Individual',
            sumInsured: 500000,
        },
        clinical: {
            chiefComplaints: diagnosisText,
            durationOfPresentAilment: '5 days',
            natureOfIllness: 'Acute',
            historyOfPresentIllness: diagnosisText,
            relevantClinicalFindings: 'As noted',
            treatmentTakenSoFar: 'None',
            vitals: { bp: '120/80', pulse: '80', temp: '98.6', spo2: '98', rr: '16' },
            diagnoses: [{
                diagnosis: diagnosisText,
                icd10Code: icd10Code,
                icd10Description: diagnosisText,
                probability: 1.0,
                reasoning: '',
                isSelected: true,
            }],
            selectedDiagnosisIndex: 0,
            proposedLineOfTreatment: {
                medical: true, surgical: false,
                intensiveCare: false, investigation: false, nonAllopathic: false,
            },
            reasonForHospitalisation: 'Requires inpatient care.',
        },
        admission: {
            dateOfAdmission: '2024-08-01',
            timeOfAdmission: '10:00',
            admissionType: 'Emergency',
            roomCategory: 'General Ward',
            expectedLengthOfStay: 5,
            expectedDaysInICU: 0,
            expectedDaysInRoom: 5,
            pastMedicalHistory: {
                diabetes: { present: false },
                hypertension: { present: false },
                heartDisease: { present: false },
                asthma: { present: false },
                epilepsy: { present: false },
                cancer: { present: false },
                kidney: { present: false },
                liver: { present: false },
                hiv: { present: false },
                alcoholism: { present: false },
                smoking: { present: false },
            },
            previousHospitalization: { wasHospitalizedBefore: false },
        },
        costEstimate: {
            roomRentPerDay: 2000, expectedRoomDays: 5, totalRoomCharges: 10000,
            icuChargesPerDay: 0, expectedIcuDays: 0, totalIcuCharges: 0,
            otCharges: 0, surgeonFee: 0, anesthetistFee: 0,
            consultantFee: 1000, investigationsEstimate: 2000,
            medicinesEstimate: 3000, consumablesEstimate: 500,
            totalEstimatedCost: 16500, amountClaimedFromInsurer: 16500,
            patientResponsibility: 0, exceedsSumInsured: false, excessAmount: 0,
            implants: [], totalImplantsCost: 0, ambulanceCharges: 0,
            miscCharges: 0, isPackageRate: false,
        },
        uploadedDocuments: [],
        declarations: {
            patient: {
                agreedToTerms: true, consentForMedicalDataSharing: true,
                agreesToPayNonPayables: true, capturedBy: 'Adversarial QA',
            },
            doctor: {
                doctorId: 'DOC001', doctorName: 'Dr. QA Test',
                doctorQualification: 'MD', doctorRegistrationNumber: 'REG99999',
                registrationCouncil: 'MCI', confirmed: true, confirmationMethod: 'in_app',
            },
            hospital: {
                authorizedSignatoryName: 'QA Director',
                designation: 'Director', hospitalSealApplied: true,
            },
        },
    };
}

// ─── adversarial case definitions ─────────────────────────────────────────────

const cases: AdversarialCase[] = [
    // ── Category A: Valid but genuinely unmapped ICD-10 codes ──────────────────
    { label: 'Tetanus',                        category: 'A', icd10Code: 'A35',   diagnosisText: 'Generalized tetanus', expectMapped: false },
    { label: 'Typhoid fever',                  category: 'A', icd10Code: 'A01',   diagnosisText: 'Typhoid fever', expectMapped: false },
    { label: 'Tuberculosis',                   category: 'A', icd10Code: 'A15',   diagnosisText: 'Pulmonary tuberculosis', expectMapped: false },
    { label: 'Malaria',                        category: 'A', icd10Code: 'B50',   diagnosisText: 'Plasmodium falciparum malaria', expectMapped: false },
    { label: 'Leptospirosis',                  category: 'A', icd10Code: 'A27',   diagnosisText: 'Leptospiral jaundice', expectMapped: false },
    { label: 'Viral encephalitis',             category: 'A', icd10Code: 'A86',   diagnosisText: 'Viral encephalitis', expectMapped: false },
    { label: 'Acute rheumatic fever',          category: 'A', icd10Code: 'I00',   diagnosisText: 'Acute rheumatic fever with carditis', expectMapped: false },
    { label: 'Hypertensive emergency',         category: 'A', icd10Code: 'I10',   diagnosisText: 'Hypertensive crisis', expectMapped: false },
    { label: 'Pulmonary embolism',             category: 'A', icd10Code: 'I26',   diagnosisText: 'Massive pulmonary embolism', expectMapped: false },
    { label: 'Aortic dissection',              category: 'A', icd10Code: 'I71',   diagnosisText: 'Type A aortic dissection', expectMapped: false },
    { label: 'Guillain-Barré syndrome',        category: 'A', icd10Code: 'G61',   diagnosisText: 'Guillain-Barré syndrome', expectMapped: false },
    { label: 'Meningitis',                     category: 'A', icd10Code: 'G03',   diagnosisText: 'Bacterial meningitis', expectMapped: false },
    { label: 'Status epilepticus',             category: 'A', icd10Code: 'G41',   diagnosisText: 'Status epilepticus', expectMapped: false },
    { label: 'Anaphylaxis',                    category: 'A', icd10Code: 'T78',   diagnosisText: 'Anaphylactic shock', expectMapped: false },
    { label: 'Acute pancreatitis',             category: 'A', icd10Code: 'K85',   diagnosisText: 'Acute pancreatitis', expectMapped: false },
    { label: 'Hepatic failure',                category: 'A', icd10Code: 'K72',   diagnosisText: 'Acute hepatic failure', expectMapped: false },
    { label: 'GI hemorrhage',                  category: 'A', icd10Code: 'K92',   diagnosisText: 'Upper GI bleeding', expectMapped: false },
    { label: 'Diabetic ketoacidosis',          category: 'A', icd10Code: 'E11',   diagnosisText: 'Type 2 diabetic ketoacidosis', expectMapped: false },
    { label: 'Hypoglycemic coma',              category: 'A', icd10Code: 'E16',   diagnosisText: 'Hypoglycemic coma', expectMapped: false },
    { label: 'Thyroid storm',                  category: 'A', icd10Code: 'E05',   diagnosisText: 'Thyroid storm / thyrotoxic crisis', expectMapped: false },
    { label: 'Eclampsia',                      category: 'A', icd10Code: 'O15',   diagnosisText: 'Eclampsia in pregnancy', expectMapped: false },
    { label: 'Postpartum hemorrhage',          category: 'A', icd10Code: 'O72',   diagnosisText: 'Postpartum hemorrhage', expectMapped: false },
    { label: 'Hip fracture',                   category: 'A', icd10Code: 'S72',   diagnosisText: 'Femoral neck fracture', expectMapped: false },
    { label: 'Spinal cord injury',             category: 'A', icd10Code: 'S14',   diagnosisText: 'Cervical spinal cord injury', expectMapped: false },
    { label: 'Acute liver failure',            category: 'A', icd10Code: 'K71',   diagnosisText: 'Drug-induced liver injury', expectMapped: false },

    // ── Category B: Boundary codes — adjacent to mapped prefixes ──────────────
    { label: 'J17 (NOT J18) — respiratory',   category: 'B', icd10Code: 'J17',   diagnosisText: 'Pneumonia in disease elsewhere classified', expectMapped: false },
    { label: 'J45 (NOT J44) — asthma',        category: 'B', icd10Code: 'J45',   diagnosisText: 'Bronchial asthma', expectMapped: false },
    { label: 'I20 (NOT I21) — angina',        category: 'B', icd10Code: 'I20',   diagnosisText: 'Unstable angina', expectMapped: false },
    { label: 'I49 (NOT I50) — arrhythmia',    category: 'B', icd10Code: 'I49',   diagnosisText: 'Ventricular fibrillation', expectMapped: false },
    { label: 'A39 (NOT A41) — meningococcal', category: 'B', icd10Code: 'A39',   diagnosisText: 'Meningococcal infection', expectMapped: false },
    { label: 'K36 (NOT K35) — other append.', category: 'B', icd10Code: 'K36',   diagnosisText: 'Other appendicitis', expectMapped: false },
    { label: 'M16 (NOT M17) — hip OA',        category: 'B', icd10Code: 'M16',   diagnosisText: 'Hip osteoarthritis', expectMapped: false },
    { label: 'I64 (NOT I63) — unspec stroke', category: 'B', icd10Code: 'I64',   diagnosisText: 'Stroke, not specified as hemorrhage or infarction', expectMapped: false },
    { label: 'N19 (NOT N18) — unspec renal',  category: 'B', icd10Code: 'N19',   diagnosisText: 'Unspecified kidney failure', expectMapped: false },
    { label: 'C33 (NOT C34) — trachea',       category: 'B', icd10Code: 'C33',   diagnosisText: 'Malignant neoplasm of trachea', expectMapped: false },
    { label: 'T30 (NOT T31) — unspec burns',  category: 'B', icd10Code: 'T30',   diagnosisText: 'Burns of unspecified extent', expectMapped: false },

    // ── Category C: Malformed / invalid code strings ───────────────────────────
    { label: 'Lowercase code',                 category: 'C', icd10Code: 'j18',   diagnosisText: 'pneumonia', expectMapped: false },
    { label: 'Code with leading space',        category: 'C', icd10Code: ' J18',  diagnosisText: 'Pneumonia', expectMapped: false },
    { label: 'Code with trailing space',       category: 'C', icd10Code: 'J18 ',  diagnosisText: 'Pneumonia', expectMapped: false },
    { label: 'Only 2 chars',                   category: 'C', icd10Code: 'J1',    diagnosisText: 'Some condition', expectMapped: false },
    { label: 'Purely numeric',                 category: 'C', icd10Code: '123',   diagnosisText: 'Some condition', expectMapped: false },
    { label: 'Special characters',             category: 'C', icd10Code: 'J18!',  diagnosisText: 'Pneumonia', expectMapped: false },
    { label: 'SQL injection attempt',          category: 'C', icd10Code: "'; DROP TABLE--", diagnosisText: 'Attack', expectMapped: false },
    { label: 'Unicode lookalike (J¹⁸)',        category: 'C', icd10Code: 'J¹8',   diagnosisText: 'Pneumonia lookalike', expectMapped: false },
    { label: 'Empty string code',              category: 'C', icd10Code: '',       diagnosisText: 'No code provided', expectMapped: false },
    { label: 'Pending ICD-10 literal',         category: 'C', icd10Code: 'Pending ICD-10', diagnosisText: 'Awaiting confirmation', expectMapped: false },
    { label: 'Selection required literal',     category: 'C', icd10Code: 'Selection required', diagnosisText: 'Not yet selected', expectMapped: false },
    { label: 'Whitespace-only code',           category: 'C', icd10Code: '   ',   diagnosisText: 'Blank', expectMapped: false },

    // ── Category D: Clinically severe but unmapped — most dangerous ────────────
    { label: 'Cardiogenic shock',              category: 'D', icd10Code: 'R57',   diagnosisText: 'Cardiogenic shock', expectMapped: false },
    { label: 'Septic shock (not A41)',         category: 'D', icd10Code: 'R65',   diagnosisText: 'Systemic inflammatory response syndrome / septic shock', expectMapped: false },
    { label: 'ARDS',                           category: 'D', icd10Code: 'J80',   diagnosisText: 'Acute respiratory distress syndrome', expectMapped: false },
    { label: 'Acute MI variant (NSTEMI)',      category: 'D', icd10Code: 'I22',   diagnosisText: 'Subsequent NSTEMI', expectMapped: false },
    { label: 'Intracranial abscess',           category: 'D', icd10Code: 'G06',   diagnosisText: 'Intracranial abscess and granuloma', expectMapped: false },
    { label: 'Acute limb ischemia',            category: 'D', icd10Code: 'I74',   diagnosisText: 'Arterial embolism lower limb', expectMapped: false },
    { label: 'Necrotizing fasciitis',          category: 'D', icd10Code: 'M72',   diagnosisText: 'Necrotizing fasciitis', expectMapped: false },
    { label: 'Multi-organ failure',            category: 'D', icd10Code: 'R68',   diagnosisText: 'Multi-organ dysfunction syndrome', expectMapped: false },
    { label: 'Rhabdomyolysis',                 category: 'D', icd10Code: 'T79',   diagnosisText: 'Rhabdomyolysis and myoglobinuria', expectMapped: false },
    { label: 'Toxic epidermal necrolysis',     category: 'D', icd10Code: 'L51',   diagnosisText: 'Stevens-Johnson Syndrome / TEN', expectMapped: false },

    // ── Category E: Empty / null-like diagnosis fields ─────────────────────────
    { label: 'No ICD + no text',              category: 'E', icd10Code: '',       diagnosisText: '', expectMapped: false },
    { label: 'Random free text only',         category: 'E', icd10Code: '',       diagnosisText: 'Patient came with pain and fever', expectMapped: false },
    { label: 'Numeric diagnosis text',        category: 'E', icd10Code: '',       diagnosisText: '12345', expectMapped: false },

    // ── Category F: Text-only (no code) but containing neutral language ─────────
    { label: 'Generic "fever" text',           category: 'F', icd10Code: '',      diagnosisText: 'Fever of unknown origin', expectMapped: false },
    { label: 'Generic "pain" text',            category: 'F', icd10Code: '',      diagnosisText: 'Abdominal pain', expectMapped: false },
    { label: 'Generic "infection" text',       category: 'F', icd10Code: '',      diagnosisText: 'Infection, unspecified', expectMapped: false },

    // ── Category G: Codes that pattern-match to a mapped prefix but are wrong ──
    { label: 'J180 (full subcode)',            category: 'G', icd10Code: 'J180',  diagnosisText: 'Pneumonia code variant', expectMapped: true },  // J18 prefix IS mapped
    { label: 'J18.9 (dot notation)',           category: 'G', icd10Code: 'J18.9', diagnosisText: 'Unspecified pneumonia', expectMapped: true },   // J18 prefix IS mapped
    { label: 'I21.0 (dot notation)',           category: 'G', icd10Code: 'I21.0', diagnosisText: 'STEMI anterior wall', expectMapped: true },    // I21 IS mapped
    { label: 'M17.1 (dot notation)',           category: 'G', icd10Code: 'M17.1', diagnosisText: 'Primary OA knee', expectMapped: true },        // M17 IS mapped
    { label: 'I61.9 (dot notation)',           category: 'G', icd10Code: 'I61.9', diagnosisText: 'ICH unspecified', expectMapped: true },        // I61 IS mapped
];

// ─── main runner ──────────────────────────────────────────────────────────────

interface TestResult {
    label: string;
    category: string;
    icd10Code: string;
    expectMapped: boolean;
    actualMapped: boolean;
    score: number;
    needsManualReview: boolean;
    passed: boolean;
    failReason?: string;
}

function runAdversarialBatch(): void {
    console.log('\n');
    console.log('═'.repeat(90));
    console.log('  AIVANA — ADVERSARIAL SAFETY QA BATCH');
    console.log('  Testing: "Does every unmapped input fail safe to needsManualReview?"');
    console.log('═'.repeat(90));
    console.log('');
    console.log('  SAFETY INVARIANT: unmapped ICD → needsManualReview=true AND score ≤ 40');
    console.log('  A "slip-through" = any case where either property is violated.');
    console.log('');

    const results: TestResult[] = [];
    let slipThroughs = 0;

    for (const tc of cases) {
        const record = buildFullRecord(tc.icd10Code, tc.diagnosisText);
        const result = computeReadiness(record, null);
        const actualMapped = isIcdMapped(tc.icd10Code || tc.diagnosisText);

        let passed = true;
        let failReason: string | undefined;

        if (!tc.expectMapped) {
            // Safety invariant check — unmapped inputs MUST fail safe
            if (result.needsManualReview === false) {
                passed = false;
                failReason = `needsManualReview=false (SLIP-THROUGH). Score=${result.score}`;
            } else if (result.score > SAFE_SCORE_CEILING) {
                passed = false;
                failReason = `score=${result.score} > ceiling of ${SAFE_SCORE_CEILING} despite unmapped condition`;
            }
        } else {
            // Mapped inputs should NOT be flagged for manual review
            if (result.needsManualReview === true) {
                passed = false;
                failReason = `needsManualReview=true but this code IS mapped (false positive)`;
            }
        }

        if (!passed) slipThroughs++;

        results.push({
            label: tc.label,
            category: tc.category,
            icd10Code: tc.icd10Code || '(empty)',
            expectMapped: tc.expectMapped,
            actualMapped,
            score: result.score,
            needsManualReview: result.needsManualReview ?? false,
            passed,
            failReason,
        });
    }

    // ── Print results table ────────────────────────────────────────────────────
    const categoryGroups = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
    const categoryNames: Record<string, string> = {
        A: 'Valid but genuinely unmapped ICD-10 codes',
        B: 'Boundary codes — adjacent to mapped prefixes',
        C: 'Malformed / invalid code strings',
        D: 'Clinically severe but unmapped (highest risk)',
        E: 'Empty / null-like diagnosis inputs',
        F: 'Text-only diagnoses with no ICD-10 code',
        G: 'Codes that prefix-match a mapped code (should PASS scoring)',
    };

    for (const cat of categoryGroups) {
        const group = results.filter(r => r.category === cat);
        if (!group.length) continue;

        console.log(`\n  ── Category ${cat}: ${categoryNames[cat]} ──`);
        console.log(`  ${'Label'.padEnd(40)} ${'Code'.padEnd(22)} ${'Mapped?'.padEnd(10)} ${'Score'.padEnd(8)} ${'Review?'.padEnd(10)} Result`);
        console.log(`  ${'-'.repeat(110)}`);

        for (const r of group) {
            const mappedStr = r.actualMapped ? 'YES' : 'NO';
            const reviewStr = r.needsManualReview ? 'YES' : 'NO';
            const resultStr = r.passed ? PASS : `${FAIL}`;
            console.log(
                `  ${r.label.padEnd(40)} ${r.icd10Code.padEnd(22)} ${mappedStr.padEnd(10)} ${String(r.score).padEnd(8)} ${reviewStr.padEnd(10)} ${resultStr}`
            );
            if (!r.passed) {
                console.log(`    ↳ Reason: ${r.failReason}`);
            }
        }
    }

    // ── Summary ───────────────────────────────────────────────────────────────
    const total = results.length;
    const passed = results.filter(r => r.passed).length;
    const failed = total - passed;

    console.log('\n');
    console.log('═'.repeat(90));
    console.log(`  ADVERSARIAL SAFETY QA SUMMARY`);
    console.log('═'.repeat(90));
    console.log(`  Total test cases   : ${total}`);
    console.log(`  Passed (safe)      : ${passed}`);
    console.log(`  Slip-throughs BUGS : ${failed}`);
    console.log(`  Safety rate        : ${((passed / total) * 100).toFixed(1)}%`);
    console.log('─'.repeat(90));

    if (failed === 0) {
        console.log('');
        console.log('  🛡️  ALL CASES FAIL SAFE. Safety invariant is VERIFIED.');
        console.log('     The engine correctly refuses to auto-score every unmapped input.');
        console.log('     It is safe to proceed to clinically-validated map expansion.');
    } else {
        console.log('');
        console.log(`  🚨 ${failed} SLIP-THROUGH BUG(S) DETECTED.`);
        console.log('     DO NOT expand the ICD-10 map until these are fixed.');
        console.log('     Each slip-through means the engine is confidently wrong on real patients.');
        console.log('');
        // Exit with non-zero for CI
        process.exit(1);
    }
    console.log('═'.repeat(90));
    console.log('');
}

runAdversarialBatch();
