import { MultiModuleTestCase } from './dynamicCaseGenerator';

export const adversarialTestCases: MultiModuleTestCase[] = [
  {
    id: 50001,
    category: 'A',
    difficulty: 'high',
    focusCategory: 'billing_complex',
    diagnosis: 'Bilateral Primary Osteoarthritis of Knee',
    code: 'M17.0',
    chiefComplaints: 'Severe pain in both knees, worse on left side. Restricted movement.',
    hpi: 'Patient has osteoarthritis in both knees. Left knee is severely deformed. Planned for left knee TKR (unilateral). History of hypertension.',
    relevantClinicalFindings: 'X-ray shows Grade IV OA in left knee, Grade II OA in right knee. Left TKR planned.',
    patientName: 'Karan Singh',
    patient: { patientName: 'Karan Singh', age: 64, gender: 'Male' },
    insurance: { policyNumber: 'STAR-ADV-01', insurerName: 'Star Health and Allied Insurance Co Ltd', tpaName: 'Medi Assist', sumInsured: 400000 },
    rawDocumentText: 'PATIENT: Karan Singh, Age: 64, Gender: Male. Policy Number: STAR-ADV-01, Insurer: Star Health, TPA: Medi Assist. Clinical Notes: Osteoarthritis of left knee (Grade IV) and right knee (Grade II). Planned for unilateral Left Total Knee Replacement (TKR). Requested Room: Single Private. Estimated Cost for Bilateral TKR Package: 380000.',
    cost: { totalEstimatedCost: 380000, wardType: 'Private' } as any, // Mismatch: document says unilateral left TKR but hospital bills for bilateral package rate (380k)
    expected: { mustFlag: ['Bilateral_Unilateral_Mismatch'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Bilateral procedure billed as unilateral mismatch case',
    realGap: 'Billing package rate mismatch: unilateral surgery billed under bilateral package',
    sourceReasoning: 'IRDAI Guidelines on billing transparency: package charges must match documented surgical scope.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Karan Singh', age: 64, gender: 'Male', policyNumber: 'STAR-ADV-01', insurerName: 'Star Health' },
      expectedReview: { mustFlag: ['Bilateral_Unilateral_Mismatch'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'M17.0',
      expectedCost: 200000, // Should be adjusted to unilateral rate
      expectedEligibility: 'query',
      expectedAppealCitations: ['unilateral Left Total Knee Replacement']
    }
  },
  {
    id: 50002,
    category: 'B',
    difficulty: 'extreme',
    focusCategory: 'denial_heavy',
    diagnosis: 'Chronic Calculous Cholecystitis with Cholelithiasis',
    code: 'K80.2',
    chiefComplaints: 'Recurrent right upper quadrant pain, postprandial dyspepsia.',
    hpi: 'Patient has history of gallstones for 2 years. Admitted for elective laparoscopic cholecystectomy. Policy in force for 731 days (inception 2024-06-01, admission 2026-06-02).',
    relevantClinicalFindings: 'USG: Multiple gallstones, thickened gallbladder wall. Liver function normal.',
    patientName: 'Meera Nair',
    patient: { patientName: 'Meera Nair', age: 42, gender: 'Female' },
    insurance: { policyNumber: 'CARE-ADV-02', insurerName: 'Care Health Insurance', tpaName: 'MDIndia', sumInsured: 300000 },
    simulatedDenialReason: 'Pre-authorization denied under Pre-Existing Disease (PED) clause 3.2. Policy is subject to a 24-month waiting period for calculus cholecystitis.',
    rawDocumentText: 'PATIENT: Meera Nair, Age: 42, Gender: Female. Policy Number: CARE-ADV-02, Insurer: Care Health Insurance. Inception Date: 2024-06-01. Admission Date: 2026-06-02. Clinical Notes: Recurrent biliary colic. Gallstones documented 2 years ago. Admitted for Laparoscopic Cholecystectomy. Estimated Cost: 110000.',
    cost: { totalEstimatedCost: 110000, wardType: 'General' } as any,
    expected: { mustFlag: [], mustNotFlag: [], shouldGenerate: true },
    notes: 'Waiting period boundary case on Day 731 (eligible as 2 years = 730 days elapsed)',
    realGap: 'Invalid denial: 2-year waiting period completed on Day 730, Day 731 is fully eligible',
    sourceReasoning: 'IRDAI Master Circular 2024: Waiting periods must be calculated strictly from inception date. 24 months elapsed.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Meera Nair', age: 42, gender: 'Female', policyNumber: 'CARE-ADV-02', insurerName: 'Care Health Insurance' },
      expectedReview: null,
      expectedCode: 'K80.2',
      expectedCost: 110000,
      expectedEligibility: 'approved',
      expectedAppealCitations: ['Inception Date: 2024-06-01', 'Admission Date: 2026-06-02', 'Policy is subject to a 24-month waiting period']
    }
  },
  {
    id: 50003,
    category: 'C',
    difficulty: 'high',
    focusCategory: 'preauth_heavy',
    diagnosis: 'Acute Gastroenteritis', // Initial diagnosis on admission
    code: 'A09.9',
    chiefComplaints: 'Severe vomiting, watery diarrhea, abdominal cramps.',
    hpi: 'Patient admitted for dehydration due to acute gastroenteritis. On Day 2, patient developed severe retrosternal crushing chest pain radiating to left arm. ECG showed ST elevation.',
    relevantClinicalFindings: 'Admitted for gastroenteritis. Upgraded to Acute Anterior Wall Myocardial Infarction. Emergency PTCA performed.',
    patientName: 'Devendra Joshi',
    patient: { patientName: 'Devendra Joshi', age: 58, gender: 'Male' },
    insurance: { policyNumber: 'HDFC-ADV-03', insurerName: 'HDFC ERGO General Insurance Co Ltd', tpaName: 'Paramount', sumInsured: 800000 },
    rawDocumentText: 'PATIENT: Devendra Joshi, Age: 58, Gender: Male. Policy Number: HDFC-ADV-03. Admitted for Acute Gastroenteritis on 2026-07-01. Day 2: patient developed crushing chest pain, diaphoresis. BP 90/60, Pulse 102/min. ECG: ST elevation in V1-V4. Trop-I positive. Diagnosis enhanced to Acute Anterior Wall Myocardial Infarction. Shifted to Cath Lab for emergency PTCA + stenting. Total cost enhanced to 345000.',
    cost: { totalEstimatedCost: 345000, wardType: 'ICU' } as any, // Initial gastroenteritis cost was 25000, enhanced to 345000
    expected: { mustFlag: ['Emergency_Enhancement_Justified'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Mid-admission diagnosis change from Gastroenteritis to Acute MI triggering cost enhancement',
    realGap: 'Clinical justification for sudden enhancement from medical management to coronary intervention',
    sourceReasoning: 'TPA claims guidelines: mid-admission cost enhancements must be supported by progressive emergency clinical findings.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Devendra Joshi', age: 58, gender: 'Male', policyNumber: 'HDFC-ADV-03', insurerName: 'HDFC ERGO General Insurance Co Ltd' },
      expectedReview: { mustFlag: ['Emergency_Enhancement_Justified'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'I21.0', // Updated expected code after enhancement
      expectedCost: 345000,
      expectedEligibility: 'approved',
      expectedAppealCitations: ['ECG: ST elevation', 'emergency PTCA', 'Diagnosis enhanced']
    }
  },
  {
    id: 50004,
    category: 'A',
    difficulty: 'high',
    focusCategory: 'preauth_heavy',
    diagnosis: 'Acute Cholecystitis',
    code: 'K81.0',
    chiefComplaints: 'Severe right upper quadrant pain, fever, vomiting.',
    hpi: 'Patient scheduled for laparoscopic cholecystectomy. Discharge summary claims successful Laparoscopic Cholecystectomy. However, the Operative Note describes conversion to Open Cholecystectomy due to dense adhesions.',
    relevantClinicalFindings: 'Discrepancy: Discharge summary says laparoscopic, OT note says open cholecystectomy.',
    patientName: 'Sunita Rao',
    patient: { patientName: 'Sunita Rao', age: 48, gender: 'Female' },
    insurance: { policyNumber: 'STAR-ADV-04', insurerName: 'Star Health and Allied Insurance Co Ltd', tpaName: 'MDIndia', sumInsured: 500000 },
    rawDocumentText: 'PATIENT: Sunita Rao, Age: 48, Gender: Female. Policy Number: STAR-ADV-04. DISCHARGE SUMMARY: Underwent Laparoscopic Cholecystectomy under GA. Recovered well. OPERATIVE (OT) NOTE: Laparoscopic port inserted. Found severe adhesions around gallbladder. Switched to Open Cholecystectomy. Subcostal incision made. Gallbladder dissected. Drainage tube kept.',
    cost: { totalEstimatedCost: 150000, wardType: 'General' } as any,
    expected: { mustFlag: ['Surgical_Technique_Conflict'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Discharge summary conflicts with the OT note (Laparoscopic vs Open)',
    realGap: 'Surgical technique conflict: discharge summary and operative notes state different techniques',
    sourceReasoning: 'Billing Audits: Open surgeries generally have different pricing and complications compared to laparoscopic ones.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Sunita Rao', age: 48, gender: 'Female', policyNumber: 'STAR-ADV-04', insurerName: 'Star Health' },
      expectedReview: { mustFlag: ['Surgical_Technique_Conflict'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'K81.0',
      expectedCost: 150000,
      expectedEligibility: 'query',
      expectedAppealCitations: ['Switched to Open Cholecystectomy', 'Laparoscopic Cholecystectomy']
    }
  },
  {
    id: 50005,
    category: 'C',
    difficulty: 'high',
    focusCategory: 'billing_complex',
    diagnosis: 'Triple Vessel Disease (IHD)',
    code: 'I25.1',
    chiefComplaints: 'Angina on exertion, dyspnea NYHA Class II.',
    hpi: 'Patient admitted for planned CABG surgery. Stayed in Deluxe Private room costing 12000 per day. Sum insured is 500000. Deluxe Private room cap is 5000/day. Hospital applied proportional deductions to implants (₹1,50,000) and medicines (₹80,000).',
    relevantClinicalFindings: 'Deluxe private room rent exceeds policy cap (1% = 5000/day). Mismatch in deduction application.',
    patientName: 'Rajesh Mehta',
    patient: { patientName: 'Rajesh Mehta', age: 67, gender: 'Male' },
    insurance: { policyNumber: 'RELIANCE-ADV-05', insurerName: 'Reliance General Insurance', tpaName: 'Paramount', sumInsured: 500000 },
    rawDocumentText: 'PATIENT: Rajesh Mehta, Age: 67, Gender: Male. Policy Number: RELIANCE-ADV-05. Sum Insured: 500000. Room Category: Deluxe Suite (12000/day). Clinical: TVD, planned CABG. Total charges: 480000 (Room rent: 60000, Surgery: 190000, Implants: 150000, Medicines: 80000). Hospital deducted 50% from Implants and Medicines proportionally.',
    cost: { totalEstimatedCost: 480000, wardType: 'Private' } as any,
    expected: { mustFlag: ['Incorrect_Proportional_Deduction'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Proportional room rent cap breach with incorrect deduction rates (medicines/implants must not have proportional deductions)',
    realGap: 'Incorrect proportional billing deductions applied to capped/non-medical items',
    sourceReasoning: 'IRDAI Master Circular 2024: Proportional deductions cannot be applied to fixed-rate items like implants, stents, or capped medicines.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Rajesh Mehta', age: 67, gender: 'Male', policyNumber: 'RELIANCE-ADV-05', insurerName: 'Reliance General Insurance' },
      expectedReview: { mustFlag: ['Incorrect_Proportional_Deduction'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'I25.1',
      expectedCost: 480000,
      expectedEligibility: 'query',
      expectedAppealCitations: ['Implants: 150000', 'Deluxe Suite (12000/day)']
    }
  },
  {
    id: 50006,
    category: 'E',
    difficulty: 'extreme',
    focusCategory: 'denial_heavy',
    diagnosis: 'Dengue Fever',
    code: 'A90',
    chiefComplaints: 'High grade fever, severe body ache, platelet count drop.',
    hpi: 'Patient claims to be admitted in Hospital A (Apollo) from 2026-07-01 to 2026-07-05. However, TPA database shows an overlapping pre-auth request for the same patient in Hospital B (Fortis) for Enteric Fever from 2026-07-03 to 2026-07-07.',
    relevantClinicalFindings: 'Overlapping hospital stays in two different locations.',
    patientName: 'Anil Verma',
    patient: { patientName: 'Anil Verma', age: 29, gender: 'Male' },
    insurance: { policyNumber: 'STAR-ADV-06', insurerName: 'Star Health and Allied Insurance Co Ltd', tpaName: 'Medi Assist', sumInsured: 300000 },
    simulatedDenialReason: 'Pre-authorization rejected due to double submission / overlapping claim detected in TPA database.',
    rawDocumentText: 'PATIENT: Anil Verma, Age: 29, Gender: Male. Policy Number: STAR-ADV-06. Admitted at Apollo Hospital for Dengue Fever. Admission: 2026-07-01. Expected Discharge: 2026-07-05. Platelets: 45,000/μL. Active pre-auth request at Fortis Hospital starting 2026-07-03 for same policy number.',
    cost: { totalEstimatedCost: 65000, wardType: 'General' } as any,
    expected: { mustFlag: ['Overlapping_Admission_Alert'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Overlapping claim fraud case, should fail or block confidently',
    realGap: 'Potential double submission: patient active in two different hospitals simultaneously',
    sourceReasoning: 'TPA Security Protocol: Overlapping admissions for the same patient under the same policy is a major fraud indicator.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Anil Verma', age: 29, gender: 'Male', policyNumber: 'STAR-ADV-06', insurerName: 'Star Health' },
      expectedReview: { mustFlag: ['Overlapping_Admission_Alert'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'A90',
      expectedCost: 65000,
      expectedEligibility: 'denied', // Should be denied or blocked
      expectedAppealCitations: ['Fortis Hospital starting 2026-07-03', 'Admission: 2026-07-01']
    }
  },
  {
    id: 50007,
    category: 'B',
    difficulty: 'high',
    focusCategory: 'preauth_heavy',
    diagnosis: 'Acute Appendicitis with Perforation',
    code: 'K35.2',
    chiefComplaints: 'Severe right iliac fossa pain, guarding, high fever, abdominal distension.',
    hpi: 'Emergency admission. Patient presented with acute abdomen, guarding, rigidity, and shock. Rushed directly to emergency laparotomy due to perforated appendix. No pre-op ultrasound or Alvarado score was recorded.',
    relevantClinicalFindings: 'Acute emergency perforated appendicitis. Rushed to emergency surgery.',
    patientName: 'Rohan Deshmukh',
    patient: { patientName: 'Rohan Deshmukh', age: 24, gender: 'Male' },
    insurance: { policyNumber: 'ICICI-ADV-07', insurerName: 'ICICI Lombard General Insurance Co Ltd', tpaName: 'IL-TPA', sumInsured: 600000 },
    rawDocumentText: 'PATIENT: Rohan Deshmukh, Age: 24, Gender: Male. Policy Number: ICICI-ADV-07. Admission: Emergency. Clinical: Severe abdominal pain x12 hours. Rigid abdomen, guarding, rebound tenderness. BP 90/60. Suspected perforated appendix. Rushed directly to OT for emergency open appendectomy. No ultrasound done due to acute surgical emergency.',
    cost: { totalEstimatedCost: 180000, wardType: 'General' } as any,
    expected: { mustFlag: [], mustNotFlag: ['USG_Justification_Required', 'Alvarado_Score_Required'], shouldGenerate: true },
    notes: 'Emergency perforation cholecystectomy/appendectomy without diagnostics (should bypass and pass gracefully)',
    realGap: 'Emergency status bypasses standard diagnostic checklist rules',
    sourceReasoning: 'IRDAI Guidelines: Life-threatening acute emergencies are exempt from non-emergency checklist diagnostic holds.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Rohan Deshmukh', age: 24, gender: 'Male', policyNumber: 'ICICI-ADV-07', insurerName: 'ICICI Lombard' },
      expectedReview: null,
      expectedCode: 'K35.2',
      expectedCost: 180000,
      expectedEligibility: 'approved',
      expectedAppealCitations: ['Admission: Emergency', 'Rushed directly to OT']
    }
  },
  {
    id: 50008,
    category: 'D',
    difficulty: 'high',
    focusCategory: 'billing_complex',
    diagnosis: 'Inguinal Hernia',
    code: 'K40.9',
    chiefComplaints: 'Right groin swelling, pain on straining.',
    hpi: 'Patient is 8 years old. Billed under a Senior Citizen Red Carpet plan, which has a 20% co-pay for ages > 60. Hospital did not apply co-pay, but TPA system flag mismatch.',
    relevantClinicalFindings: 'Patient age 8 is inconsistent with Senior Citizen policy plan.',
    patientName: 'Aarav Gupta',
    patient: { patientName: 'Aarav Gupta', age: 8, gender: 'Male' },
    insurance: { policyNumber: 'STAR-ADV-08', insurerName: 'Star Health and Allied Insurance Co Ltd', tpaName: 'Medi Assist', sumInsured: 400000 },
    rawDocumentText: 'PATIENT: Aarav Gupta, Age: 8, Gender: Male. Policy Number: STAR-ADV-08. Insurer: Star Health. Plan: Senior Citizen Red Carpet. Diagnosis: Right Inguinal Hernia, planned Hernioplasty. Estimated Cost: 95000.',
    cost: { totalEstimatedCost: 95000, wardType: 'General' } as any,
    expected: { mustFlag: ['Policy_Age_Mismatch'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Pediatric patient under a senior citizen policy plan',
    realGap: 'Policy age mismatch: child listed under senior citizen insurance plan',
    sourceReasoning: 'TPA Rule Engine: Policy plans are age-locked. A child cannot be primary beneficiary under senior citizen rules.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Aarav Gupta', age: 8, gender: 'Male', policyNumber: 'STAR-ADV-08', insurerName: 'Star Health' },
      expectedReview: { mustFlag: ['Policy_Age_Mismatch'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'K40.9',
      expectedCost: 95000,
      expectedEligibility: 'query',
      expectedAppealCitations: ['Aarav Gupta, Age: 8', 'Senior Citizen Red Carpet']
    }
  },
  {
    id: 50009,
    category: 'C',
    difficulty: 'high',
    focusCategory: 'billing_complex',
    diagnosis: 'Lumbar Radiculopathy',
    code: 'M54.16',
    chiefComplaints: 'Severe radiating low back pain, numbness in right leg.',
    hpi: 'Patient admitted for conservative management (physiotherapy, traction, NSAIDs). Billed under surgical CPT package for "Lumbar Laminectomy". No surgery was performed.',
    relevantClinicalFindings: 'Conservative management only. Billed as surgical intervention.',
    patientName: 'Devanand Rao',
    patient: { patientName: 'Devanand Rao', age: 52, gender: 'Male' },
    insurance: { policyNumber: 'HDFC-ADV-09', insurerName: 'HDFC ERGO General Insurance Co Ltd', tpaName: 'Paramount', sumInsured: 500000 },
    rawDocumentText: 'PATIENT: Devanand Rao, Age: 52, Gender: Male. Policy Number: HDFC-ADV-09. Admitted for Lumbar Radiculopathy. Line of treatment: Conservative (Tab Ultraacet, Physiotherapy, pelvic traction). Billed CPT code: 63030 (Lumbar Laminectomy/Discectomy). Total claimed amount: 165000.',
    cost: { totalEstimatedCost: 165000, wardType: 'General' } as any,
    expected: { mustFlag: ['Line_Of_Treatment_Billing_Mismatch'], mustNotFlag: [], shouldGenerate: true },
    notes: 'Conservative medical treatment billed under surgical CPT package rate',
    realGap: 'Line of treatment billing mismatch: conservative medical care billed under surgery package',
    sourceReasoning: 'IRDAI Guidelines: Billing must correspond to the actual line of treatment. Surgical package billing for conservative care is unadmissible.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Devanand Rao', age: 52, gender: 'Male', policyNumber: 'HDFC-ADV-09', insurerName: 'HDFC ERGO General Insurance Co Ltd' },
      expectedReview: { mustFlag: ['Line_Of_Treatment_Billing_Mismatch'], mustNotFlag: [], shouldGenerate: true },
      expectedCode: 'M54.16',
      expectedCost: 25000, // Should be adjusted to conservative rate
      expectedEligibility: 'query',
      expectedAppealCitations: ['Conservative (Tab Ultraacet, Physiotherapy, pelvic traction)', 'Billed CPT code: 63030']
    }
  },
  {
    id: 50010,
    category: 'B',
    difficulty: 'high',
    focusCategory: 'denial_heavy',
    diagnosis: 'Maternity LSCS Delivery',
    code: 'O82',
    chiefComplaints: 'Full term pregnancy, labor pain, history of Gestational Diabetes (GDM).',
    hpi: 'Pregnancy at 38 weeks. Patient has Gestational Diabetes Mellitus (GDM) diagnosed at 24 weeks. Admitted for repeat LSCS. TPA denied claim, stating GDM is a pre-existing condition (PED) subject to a 3-year waiting period.',
    relevantClinicalFindings: 'Gestational Diabetes Mellitus diagnosed during this pregnancy.',
    patientName: 'Komal Patel',
    patient: { patientName: 'Komal Patel', age: 29, gender: 'Female' },
    insurance: { policyNumber: 'CARE-ADV-10', insurerName: 'Care Health Insurance', tpaName: 'MDIndia', sumInsured: 400000 },
    simulatedDenialReason: 'Maternity cashless pre-auth denied due to Pre-Existing Disease (Gestational Diabetes Mellitus) within the 3-year waiting period.',
    rawDocumentText: 'PATIENT: Komal Patel, Age: 29, Gender: Female. Policy Number: CARE-ADV-10. Diagnosis: Pregnancy at 38 weeks, GDM on insulin. Planned repeat LSCS. Inception: 2025-05-01. Admission: 2026-06-02. TPA denied cashless citing GDM PED waiting period violation.',
    cost: { totalEstimatedCost: 130000, wardType: 'Private' } as any,
    expected: { mustFlag: [], mustNotFlag: ['GDM_PED_Exclusion'], shouldGenerate: true },
    notes: 'Gestational Diabetes is temporary pregnancy condition, NOT a chronic PED (should overturn denial)',
    realGap: 'Invalid TPA denial: GDM is a gestational condition, not a pre-existing chronic disease',
    sourceReasoning: 'IRDAI Guidelines: Pregnancy-related temporary conditions (like GDM or gestational hypertension) cannot be classified as chronic pre-existing diseases.',
    expectedAnswer: {
      expectedExtraction: { patientName: 'Komal Patel', age: 29, gender: 'Female', policyNumber: 'CARE-ADV-10', insurerName: 'Care Health Insurance' },
      expectedReview: null,
      expectedCode: 'O82',
      expectedCost: 130000,
      expectedEligibility: 'approved',
      expectedAppealCitations: ['Diagnosis: Pregnancy at 38 weeks, GDM on insulin', 'GDM PED waiting period violation']
    }
  }
];
